### ISSUE TITLE
There is no API or any other thing that would make it functional.

### ISSUE THREAD

**Issue by Yeetface513** [yourlostitems/yourlostitems.github.io#14]
**Is your feature request related to a problem? Please describe.**
The API has not been created, meaning item requests cannot be processed, essentially making the website useless.

**Describe the solution you'd like**
Create a functioning API

**Describe alternatives you've considered**
Another solution such as a DB

**Additional context**
You have been "working on" this for over a year now

**Comment by Yeetface513** [comment]
DO IT RAAH

**Comment by uimaxbai1** [comment]
That'd be great.

**Comment by Yeetface513** [comment]
![thumbnail_image](https://github.com/yourlostitems/yourlostitems.github.io/assets/123550198/40f9fef7-8df1-426d-9fe9-1a2f80e45610)
